Repository alercebroker/ztf_explorer, pull requests merged in 2020-08, with the labels that each got.

#240 Feature/error handling
  api/catshtm_api.js
  api/tns_api.js
  api/ztf_api.js
  components/cardAladin.vue
  components/cardBasicInformation.vue
  components/cardClassifiers.vue
  components/cardCrossMatches.vue
  components/cardLightCurve.vue
  components/cardMagStats.vue
  components/cardStamps.vue
  layouts/error.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  pages/object/_oid.vue
  plugins/axios.js
  store/features.js
  store/filters.js
  store/lightcurve.js
  store/object.js
  store/objects.js
  store/probabilities.js
  store/stats.js
  store/tns.js
  store/xmatches.js
  utils/store-accessor.js
Labels: Critical, enhancement

#241 added ranking
  store/filters.js
Labels: Critical, enhancement

#243 Showing first avro stamp
  pages/object/_oid.vue
Labels: Critical, enhancement

#242 Added default probability desc to result table
  store/pagination.js
Labels: Critical, bug

#270 Fix bugs #234 and #236
  pages/index.vue
  store/filters.js
Labels: bug

#273 Bug/change object
  components/cardLightCurve.vue
  components/cardMagStats.vue
  pages/index.vue
  store/filters.js
  store/object.js
Labels: bug

#274 fix empty string values added to query string
  plugins/axios.js
Labels: bug

#278 added the feature to select detection from stamps and lightcurve
  components/cardLightCurve.vue
  components/cardStamps.vue
  pages/object/_oid.vue
  store/lightcurve.js
Labels: Critical, enhancement

#277 Added object list
  components/objectList.vue
  components/simplePagination.vue
  layouts/oid.vue
  pages/index.vue
  pages/object/_oid.vue
  store/object.js
  store/pagination.js
Labels: enhancement

#283 Improvements in lightcurve and search by list of oids
  components/cardLightCurve.vue
  package.json
  pages/object/_oid.vue
  store/filters.js
Labels: Critical, enhancement
